download_urls = ["https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"]
using_configure_and_make = true
configure_options = "--prefix=/usr --without-guile --host=$(uname -m)-lfs-linux-gnu --build=$(build-aux/config.guess)"
make_install_args = "DESTDIR=$ROOTFS"