download_urls = ["https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.xz"]
using_configure_and_make = true
configure_options = "--prefix=/usr --host=$(uname -m)-lfs-linux-gnu"
make_install_args = "DESTDIR=$ROOTFS"