#!/bin/busybox sh

PATH="/bin:/usr/bin"

/bin/busybox --install /bin

mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sys /sys -o nosuid,noexec,nodev
mount -t devtmpfs dev /dev
mkdir /dev/pts
mkdir /dev/shm
mkdir -p /proc/sys/kernel/
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
echo -n "Starting mdev: "
/sbin/mdev -s
echo -n "Mounting devpts: "
mount -t devpts none /dev/pts

if [ -x /sbin/hwclock ] && [ -e /dev/rtc0 ]; then
	echo -n "Setting system clock: "
	hwclock --hctosys --utc
fi


mount / -o remount,rw

echo -n "Linking /var/tmp and /tmp: "
ln -s ../tmp /var/tmp


echo -n "Cleaning up system: "
rm -rf /var/run/*
> /var/run/utmp
touch /var/log/wtmp
touch /var/log/messages
chmod 0664 /var/run/utmp
chmod 0664 /var/log/wtmp
chmod 0660 /var/log/messages
rm -rf /tmp/*


echo -n "Setting up interface lo: "
ifconfig lo up 127.0.0.1
busybox --install /bin
echo 0 > /proc/sys/kernel/printk

echo "Welcome to init ram filesystem :)"
exec /bin/busybox sh