#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

/bin/busybox --install /bin

#mount -t devtmpfs dev /dev
mount -n -t tmpfs none /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

echo 0 > /proc/sys/kernel/printk
mkdir /dev/pts
mkdir /dev/shm
mkdir -p /proc/sys/kernel/
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
echo -n "Starting mdev: "
/sbin/mdev -s
echo -n "Mounting devpts: "
mount -t devpts none /dev/pts

if [ -x /sbin/hwclock ] && [ -e /dev/rtc0 ]; then
	echo -n "Setting system clock: "
	hwclock --hctosys --utc
fi


mount / -o remount,rw

echo -n "Linking /var/tmp and /tmp: "
ln -s ../tmp /var/tmp


echo -n "Cleaning up system: "
rm -rf /var/run/*
> /var/run/utmp
touch /var/log/wtmp
touch /var/log/messages
chmod 0664 /var/run/utmp
chmod 0664 /var/log/wtmp
chmod 0660 /var/log/messages
rm -rf /tmp/*


echo -n "Setting up interface lo: "
ifconfig lo up 127.0.0.1
busybox --install /bin

echo "Welcome to init ram filesystem :)"
setsid sh -c 'exec sh </dev/ttyS0 2>&1'
