name: "Run tests"
on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          sudo apt-get update && sudo apt-get install -y \
            git make gcc rsync bison flex cpio bc libelf-dev gawk fdisk wget lbzip2 \
            xz-utils dosfstools libssl-dev libncurses-dev qemu-system-x86
      - name: "build"
        run: |
          make clean
          make